package wdk0.com.youdeliao.model;

public class Post {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.ID
     *
     * @mbg.generated Wed Sep 16 18:52:40 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.TITLE
     *
     * @mbg.generated Wed Sep 16 18:52:40 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.GMT_CREATE
     *
     * @mbg.generated Wed Sep 16 18:52:40 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.GMT_MODIFIED
     *
     * @mbg.generated Wed Sep 16 18:52:40 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.CREATOR
     *
     * @mbg.generated Wed Sep 16 18:52:40 CST 2020
     */
    private Integer creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.COMMENT_COUNT
     *
     * @mbg.generated Wed Sep 16 18:52:40 CST 2020
     */
    private Integer commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.VIEW_COUNT
     *
     * @mbg.generated Wed Sep 16 18:52:40 CST 2020
     */
    private Integer viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.LIKE_COUNT
     *
     * @mbg.generated Wed Sep 16 18:52:40 CST 2020
     */
    private Integer likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.TAG
     *
     * @mbg.generated Wed Sep 16 18:52:40 CST 2020
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.DESCRIPTION
     *
     * @mbg.generated Wed Sep 16 18:52:40 CST 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.ID
     *
     * @return the value of post.ID
     *
     * @mbg.generated Wed Sep 16 18:52:40 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.ID
     *
     * @param id the value for post.ID
     *
     * @mbg.generated Wed Sep 16 18:52:40 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.TITLE
     *
     * @return the value of post.TITLE
     *
     * @mbg.generated Wed Sep 16 18:52:40 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.TITLE
     *
     * @param title the value for post.TITLE
     *
     * @mbg.generated Wed Sep 16 18:52:40 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.GMT_CREATE
     *
     * @return the value of post.GMT_CREATE
     *
     * @mbg.generated Wed Sep 16 18:52:40 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.GMT_CREATE
     *
     * @param gmtCreate the value for post.GMT_CREATE
     *
     * @mbg.generated Wed Sep 16 18:52:40 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.GMT_MODIFIED
     *
     * @return the value of post.GMT_MODIFIED
     *
     * @mbg.generated Wed Sep 16 18:52:40 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.GMT_MODIFIED
     *
     * @param gmtModified the value for post.GMT_MODIFIED
     *
     * @mbg.generated Wed Sep 16 18:52:40 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.CREATOR
     *
     * @return the value of post.CREATOR
     *
     * @mbg.generated Wed Sep 16 18:52:40 CST 2020
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.CREATOR
     *
     * @param creator the value for post.CREATOR
     *
     * @mbg.generated Wed Sep 16 18:52:40 CST 2020
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.COMMENT_COUNT
     *
     * @return the value of post.COMMENT_COUNT
     *
     * @mbg.generated Wed Sep 16 18:52:40 CST 2020
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.COMMENT_COUNT
     *
     * @param commentCount the value for post.COMMENT_COUNT
     *
     * @mbg.generated Wed Sep 16 18:52:40 CST 2020
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.VIEW_COUNT
     *
     * @return the value of post.VIEW_COUNT
     *
     * @mbg.generated Wed Sep 16 18:52:40 CST 2020
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.VIEW_COUNT
     *
     * @param viewCount the value for post.VIEW_COUNT
     *
     * @mbg.generated Wed Sep 16 18:52:40 CST 2020
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.LIKE_COUNT
     *
     * @return the value of post.LIKE_COUNT
     *
     * @mbg.generated Wed Sep 16 18:52:40 CST 2020
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.LIKE_COUNT
     *
     * @param likeCount the value for post.LIKE_COUNT
     *
     * @mbg.generated Wed Sep 16 18:52:40 CST 2020
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.TAG
     *
     * @return the value of post.TAG
     *
     * @mbg.generated Wed Sep 16 18:52:40 CST 2020
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.TAG
     *
     * @param tag the value for post.TAG
     *
     * @mbg.generated Wed Sep 16 18:52:40 CST 2020
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.DESCRIPTION
     *
     * @return the value of post.DESCRIPTION
     *
     * @mbg.generated Wed Sep 16 18:52:40 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.DESCRIPTION
     *
     * @param description the value for post.DESCRIPTION
     *
     * @mbg.generated Wed Sep 16 18:52:40 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}